# Request an environment that provides sudo (that goes with larger containers)
# and a minimal language environment.
sudo: true
language: rust
rust: nightly

cache: cargo

os:
  - windows
  - linux
  - osx

env:
  global:
    - RUST_BACKTRACE=1

before_install:
  # Check how much space we've got on this machine.
  - df -h

script:
  - ./init-wasm.sh
  - source ~/.cargo/env
  - ./test-all.sh
  - ./build-runtime.sh
  - ./build-node.sh

after_script:
  # Check how much free disk space left after the build
  - df -h
